name: Publish Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build_volatility_for_windows:
    name: build volatility to exe format for windows
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
        python-version: '2.6' 

    - run: python2 --version