name: Publish Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build_volatility_for_windows:
    name: build volatility to exe format for windows
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v2

    - uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'

    - run: python --version